version: 0.0
os: linux
files:
 - source: /index.html
   destination: /var/www/html/
 - source: /_config.yml
   destination: /var/www/html/
 - source: css
   destination: /var/www/html/css/
 - source: images
   destination: /var/www/html/images/   
hooks:
   Applicationstart:
    - location: script/restart.sh
      timeout: 300
      runas: root
